### ISSUE TITLE
Port over Gravatar D7 module to Backdrop

### ISSUE THREAD

**Issue by mgbellaire** [hb5co/hb5co#28]
Using this doc to port it over: https://api.backdropcms.org/node/28621

**Comment by mgbellaire** [comment]
So far, I've managed to moved over every variable to the new JSON config, and gotten the administration page to save properly.

**Comment by shrop** [comment]
Very nice!

**Comment by mgbellaire** [comment]
Still going well on the porting of Gravatar module. Learning a lot! Two things I need to figure out is why the creation of the url to the given Gravatar avatar is only being set as the root url.

**Comment by shrop** [comment]
Thanks for the update!

**Comment by mgbellaire** [comment]
Port is finished over at github.com/hb5co/gravatar
