### ISSUE TITLE
Make a nice footer to add some basic content

### ISSUE THREAD

**Issue by shrop** [hb5co/hb5co#48]
See example from http://getpiper.com. Maybe something like this so we can add standard footer stuffs.

<img src="https://www.evernote.com/shard/s1/sh/67581549-3bef-4890-9967-9965dcaeb3e7/d16a940ed431bb58422c8d2084a7c526/deep/0/getpiper.com-footer.png" alt="getpiper.com%20footer" />

Relates to #21

**Comment by shrop** [comment]
@bfodeke, @deetergp has a bunch of footer stuff ready for styling. Check the home page footer.

**Comment by bfodeke** [comment]
The basic of the footer is in place, just need to do some tweaking

**Comment by shrop** [comment]
Think we are good to close this one.
