### ISSUE TITLE
Setup an RSS feed for the blog

### ISSUE THREAD

**Issue by shrop** [hb5co/hb5co#74]

**Comment by shrop** [comment]
The blog page has http://hb5.co/blog.xml

Maybe just add an rss link in the footer

**Comment by shrop** [comment]
Added "Blog RSS Feed" link in the footer/social menu.

When icons are added here, could just have an rss icon. like. http://www.endlessicons.com/wp-content/uploads/2012/10/rss-feed-icon-614x460.png

**Comment by mgbellaire** [comment]
sweet! :)
