### ISSUE TITLE
Setup the hb5 logo with green circle background in the primary nav

### ISSUE THREAD

**Issue by shrop** [hb5co/hb5co#75]
@tecto suggested having the "hb5" in the primary nav look like the hb5 logo with a green circle around it, found on the home page. Seem like a great suggestions.

<img src="https://www.evernote.com/shard/s1/sh/79d40afe-e18a-4138-abbf-425b7ff8e9f2/c78ada5fc8d02e735b94d1fad497b141/deep/0/hb5-primary-nav-logo.png" alt="hb5%20primary%20nav%20logo" />

<img src="https://www.evernote.com/shard/s1/sh/9aab7ae7-5a7e-4205-a9ee-3bcd59c83f25/dbc634663f8982928ba494dc370df8ba/deep/0/home-page-hb5-logo.png" alt="home%20page%20hb5%20logo" />

**Comment by bfodeke** [comment]
I've implemented a slight variation to this and I want to get everyone thoughts on it.

It looks like this on the home page: 
![image](https://cloud.githubusercontent.com/assets/845372/6650748/419a832e-c9f9-11e4-8d0c-6a3faf506b15.png)

Then, when you scroll up, it animates to being smaller http://cl.ly/image/0e343f2d2I2H

**Comment by shrop** [comment]
@bfodeke I like it very much!

**Comment by mgbellaire** [comment]
@bfodeke That looks great!

**Comment by shrop** [comment]
closing.. all good!
