### ISSUE TITLE
Apply a circular image mask to author avatars

### ISSUE THREAD

**Issue by deetergp** [hb5co/hb5co#76]
It might be a nice addition to have author avatars be circular, at least on blog posts.

Thoughts?

**Comment by shrop** [comment]
yep.. I thought that was already the plan

**Comment by deetergp** [comment]
My mistake. I will delete the ticket…

**Comment by shrop** [comment]
Why delete the ticket?

**Comment by deetergp** [comment]
I thought it was a dupe, but we don't already have a ticket for this, so I'm going to leave it.

Nothing to see here, please move along…

**Comment by bfodeke** [comment]
Done. Circles everywhere
